apiVersion: v1
kind: Pod
metadata:
  name: dev-python
  namespace: lumuscar-jobs
  labels:
    app: dev-python
    type: development
spec:
  restartPolicy: Always
  containers:
  - name: python-dev
    image: python:3.13-bookworm
    command:
      - /bin/bash
      - -c
      - |
        # Configure HTTP proxy
        export HTTP_PROXY=PROXY_URL_PLACEHOLDER
        export HTTPS_PROXY=PROXY_URL_PLACEHOLDER
        export NO_PROXY=localhost,127.0.0.1,.svc,.cluster.local

        # Update package lists
        apt-get update

        # Install development tools
        apt-get install -y \
          curl \
          wget \
          git \
          vim \
          nano \
          tmux \
          zsh \
          build-essential \
          sudo \
          ssh \
          ca-certificates \
          gcc \
          g++ \
          make \
          libssl-dev \
          libffi-dev \
          libsqlite3-dev \
          libbz2-dev \
          libreadline-dev \
          libncurses5-dev \
          libgdbm-dev \
          liblzma-dev

        # Upgrade pip and install common packages
        pip install --upgrade pip setuptools wheel

        # Install development tools
        pip install \
          pytest \
          pytest-cov \
          black \
          flake8 \
          mypy \
          pylint \
          ipython \
          jupyter \
          jupyterlab \
          requests \
          httpx \
          aiohttp \
          pandas \
          numpy \
          matplotlib \
          poetry \
          pipenv \
          virtualenv

        # Install pyenv for multiple Python versions
        curl https://pyenv.run | bash

        # Install Task (build automation)
        curl -sL https://taskfile.dev/install.sh | sh -s -- -b /usr/local/bin

        # Setup workspace
        mkdir -p /workspace
        cd /workspace

        echo "Python development environment ready!"
        echo "Installed Python version: $(python --version)"
        echo "Workspace: /workspace"

        # Keep container running
        sleep infinity
    env:
    - name: HTTP_PROXY
      value: "PROXY_URL_PLACEHOLDER"
    - name: HTTPS_PROXY
      value: "PROXY_URL_PLACEHOLDER"
    - name: NO_PROXY
      value: "localhost,127.0.0.1,.svc,.cluster.local"
    - name: PYTHONPATH
      value: "/workspace"
    - name: PYENV_ROOT
      value: "/workspace/.pyenv"
    - name: PATH
      value: "/workspace/.pyenv/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin"
    volumeMounts:
    - name: workspace
      mountPath: /workspace
    resources:
      requests:
        memory: "8Gi"
        cpu: "4000m"
      limits:
        memory: "32Gi"
        cpu: "16000m"
  volumes:
  - name: workspace
    persistentVolumeClaim:
      claimName: dev-python-workspace
